---
language: node_js
node_js:
  - "10"

dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

script:
<<<<<<< HEAD
  - npm install
  - npm run lint:hbs
  - npm run lint:js
=======
>>>>>>> 2f8d08c... v3.15.1...v3.17.0
  - npm test

install:
  npm install -g surge

before_deploy:
  - npm run build
  - mv dist/index.html dist/200.html

deploy:
  provider: surge
  project: ./dist
  skip_cleanup: true
  domain: https://powerlifter.surge.sh
