---
language: node_js
node_js:
  - "10"

dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

script:
  - npm test

install:
  npm install -g surge
  npm install -g npm-run-all

before_deploy:
  - npm run build
  - mv dist/index.html dist/200.html

deploy:
  provider: surge
  project: ./dist
  skip_cleanup: true
  domain: https://powerlifter.surge.sh
